### ISSUE TITLE
Uncaught Error: Call to a member function find() on bool

### ISSUE THREAD

**Issue by ImASadBoy** [hawkiq/PSNApi#1]
https://imgur.com/a/DXAHe1S This is the folder, I've installed PHP Simple HTML DOM Parser, and the code is simply the example.php file

https://pastebin.com/BAfU70Yn This is the error output from example.php.

**Comment by hawkiq** [comment]
> 
> 
> https://imgur.com/a/DXAHe1S This is the folder, I've installed PHP Simple HTML DOM Parser, and the code is simply the example.php file
> 
> https://pastebin.com/BAfU70Yn This is the error output from example.php.


@ImASadBoy 
I think its maybe some error in your side maybe path or PHP version, your files should be minimum like this
https://imgur.com/BIuTOWG
Ive tested My project and its working as it should 
Please let me know any updated , if your problem solved don't forget to close the issue
Have a nice day

**Comment by ImASadBoy** [comment]
I tested it on my main server and it is now working, probably a problem with that free host, thank you very much for everything!!
